apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-psql-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-psql
  template:
    metadata:
      labels:
        app: flask-psql
    spec:
      containers:
      - name: flask-psql-container
        image: 637423378523.dkr.ecr.ap-south-1.amazonaws.com/dev/psql:latest
        ports:
        - containerPort: 5000  
        env:
        - name: DB_HOST
          value: "database-1.c5uqgyeys3rg.ap-south-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "database-1"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "4HV9kBVHtlnKcP3JleHZ"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-psql-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-psql
