name: Build and Push to ECR
on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using secrets stored in GitHub
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build and tag the Docker image
      - name: Build and tag Docker image
        run: |
          docker build -t flask-psql:latest .  # Build Docker image
          docker tag flask-psql:latest 637423378523.dkr.ecr.ap-south-1.amazonaws.com/dev/psql:latest  # Tag for ECR

      # Step 5: Push the Docker image to Amazon ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 637423378523.dkr.ecr.ap-south-1.amazonaws.com/dev/psql:latest  # Push to ECR